USE [ILP]
GO

/****** Object:  Table [dbo].[GR3_RTTUser]    Script Date: 03/05/2012 08:11:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GR3_RTTUser](
	[UserID] [int] IDENTITY(100,1) NOT NULL,
	[UserName] [varchar](50) NOT NULL,
	[DOJ] [nvarchar](50) NULL,
	[EmailID] [varchar](50) NOT NULL,
	[Address] [nvarchar](50) NULL,
	[Password] [nvarchar](50) NULL,
	[ContactNo] [varchar](50) NULL,
	[Alt_ContactNo] [varchar](50) NULL,
	[User_Type] [varchar](50) NULL,
 CONSTRAINT [PK_GR3_RTTUser] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [uk1] UNIQUE NONCLUSTERED 
(
	[EmailID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [uk2] UNIQUE NONCLUSTERED 
(
	[ContactNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

